const PegawaiActionTypes = {
  IS_EMAIL_EXIST: "IS_EMAIL_EXIST",
  TOGGLE_SHOW_MODAL_ADD_PEGAWAI: "TOGGLE_SHOW_MODAL_ADD_PEGAWAI",
  TOGGLE_SHOW_MODAL_UPDATE_PEGAWAI: "TOGGLE_SHOW_MODAL_UPDATE_PEGAWAI",
  TOGGLE_SHOW_MODAL_DELETE_PEGAWAI: "TOGGLE_SHOW_MODAL_DELETE_PEGAWAI",

  SET_INPUT_PROFILE: "SET_INPUT_PROFILE",
  REMOVE_INPUT_PROFILE: "REMOVE_INPUT_PROFILE",
  TOGGLE_IS_UPLOADING: "TOGGLE_IS_UPLOADING",
};

export default PegawaiActionTypes;
