const PembayaranActionTypes = {
  FETCH_PEMBAYARAN_START: "FETCH_PEMBAYARAN_START",
  FETCH_PEMBAYARAN_SUCCESS: "FETCH_PEMBAYARAN_SUCCESS",
  FETCH_PEMBAYARAN_FAILURE: "FETCH_PEMBAYARAN_FAILURE",
  REMOVE_DATA_PEMBAYARAN: "REMOVE_DATA_PEMBAYARAN",
};

export default PembayaranActionTypes;
