const KategoriMenuActionTypes = {
  FETCH_KATEGORI_MENU_START: "FETCH_KATEGORI_MENU_START",
  FETCH_KATEGORI_MENU_SUCCESS: "FETCH_KATEGORI_MENU_SUCCESS",
  FETCH_KATEGORI_MENU_FAILURE: "FETCH_KATEGORI_MENU_FAILURE",
  TOGGLE_SHOW_MODAL_ADD_KATEGORI_MENU: "TOGGLE_SHOW_MODAL_ADD_KATEGORI_MENU",
  TOGGLE_SHOW_MODAL_DELETE_KATEGORI_MENU:
    "TOGGLE_SHOW_MODAL_DELETE_KATEGORI_MENU",
  SET_INPUT_PROFILE_KATEGORI_MENU: "SET_INPUT_PROFILE_KATEGORI_MENU",
  REMOVE_INPUT_PROFILE_KATEGORI_MENU: "REMOVE_INPUT_PROFILE_KATEGORI_MENU",
  TOGGLE_IS_UPLOADING_KATEGORI_MENU: "TOGGLE_IS_UPLOADING_KATEGORI_MENU",
  SET_DELETE_KATEGORI_BY_ID: "SET_DELETE_KATEGORI_BY_ID",
  REMOVE_DELETE_KATEGORI_BY_ID: "REMOVE_DELETE_KATEGORI_BY_ID",
};

export default KategoriMenuActionTypes;
