const KategoriMenuActionTypes = {
  FETCH_KATEGORI_MENU_START: "FETCH_KATEGORI_MENU_START",
  FETCH_KATEGORI_MENU_SUCCESS: "FETCH_KATEGORI_MENU_SUCCESS",
  FETCH_KATEGORI_MENU_FAILURE: "FETCH_KATEGORI_MENU_FAILURE",
  SET_CURRENT_KATEGORI_MENU: "SET_CURRENT_KATEGORI_MENU",
  SET_CURRENT_KATEGORI_MENU_TO_DEFAULT: "SET_CURRENT_KATEGORI_MENU_TO_DEFAULT",
};

export default KategoriMenuActionTypes;
