const KategoriMenuActionTypes = {
  FETCH_KATEGORI_MENU_START: "FETCH_KATEGORI_MENU_START",
  FETCH_KATEGORI_MENU_SUCCESS: "FETCH_KATEGORI_MENU_SUCCESS",
  FETCH_KATEGORI_MENU_FAILURE: "FETCH_KATEGORI_MENU_FAILURE",
  TOGGLE_SHOW_MODAL_ADD_KATEGORI_MENU: "TOGGLE_SHOW_MODAL_ADD_KATEGORI_MENU",
  SET_INPUT_PROFILE: "SET_INPUT_PROFILE",
  REMOVE_INPUT_PROFILE: "REMOVE_INPUT_PROFILE",
  TOGGLE_IS_UPLOADING: "TOGGLE_IS_UPLOADING",
};

export default KategoriMenuActionTypes;
