const ReportActionTypes = {
  FETCH_REPORT_START: "FETCH_REPORT_START",
  FETCH_REPORT_SUCCESS: "FETCH_REPORT_SUCCESS",
  FETCH_REPORT_FAILURE: "FETCH_REPORT_FAILURE",
  REMOVE_DATA_REPORT: "REMOVE_DATA_REPORT",
};

export default ReportActionTypes;
