const ListPesananActionTypes = {
  FETCH_LIST_PESANAN_START: "FETCH_LIST_PESANAN_START",
  FETCH_LIST_PESANAN_SUCCESS: "FETCH_LIST_PESANAN_SUCCESS",
  FETCH_LIST_PESANAN_FAILURE: "FETCH_LIST_PESANAN_FAILURE",
  TOGGLE_IS_UPLOADING_LIST_PESANAN: "TOGGLE_IS_UPLOADING_LIST_PESANAN",
};

export default ListPesananActionTypes;
