const ListPesananActionTypes = {
  // START HANDLING FETCHING LIST PESANAN
  FETCH_LIST_PESANAN_START: "FETCH_LIST_PESANAN_START",
  FETCH_LIST_PESANAN_SUCCESS: "FETCH_LIST_PESANAN_SUCCESS",
  FETCH_LIST_PESANAN_FAILURE: "FETCH_LIST_PESANAN_FAILURE",
  REMOVE_LIST_PESANAN: "REMOVE_LIST_PESANAN",
  // END HANDLING FETCHING LIST PESANAN
  // START HANDLING MODAL
  TOGGLE_LIST_PESANAN_MODAL_HIDDEN: "TOGGLE_LIST_PESANAN_MODAL_HIDDEN",
  TOGGLE_LIST_PESANAN_DELETE_MODAL_HIDDEN:
    "TOGGLE_LIST_PESANAN_DELETE_MODAL_HIDDEN",
  TOGGLE_LIST_PESANAN_LIHAT_MODAL_HIDDEN:
    "TOGGLE_LIST_PESANAN_LIHAT_MODAL_HIDDEN",
  // END HANDLING MODAL
  // START HANDLING UTILS
  TOGGLE_IS_UPLOADING_LIST_PESANAN: "TOGGLE_IS_UPLOADING_LIST_PESANAN",
  // END HANDLING UTILS
};

export default ListPesananActionTypes;
