const PesananUtilsActionTypes = {
  TOGGLE_CHECKOUT_MODAL_HIDDEN: "TOGGLE_CHECKOUT_MODAL_HIDDEN",
  TOGGLE_LIST_PESANAN_MODAL_HIDDEN: "TOGGLE_LIST_PESANAN_MODAL_HIDDEN",
  TOGGLE_IS_UPLOADING_PESANAN: "TOGGLE_IS_UPLOADING_PESANAN",
};

export default PesananUtilsActionTypes;
