const PesananActionTypes = {
  ADD_ITEM_PESANAN: "ADD_ITEM_PESANAN",
  REMOVE_ITEM_PESANAN: "REMOVE_ITEM_PESANAN",
  CLEAR_ITEM_FROM_PESANAN: "CLEAR_ITEM_FROM_PESANAN",
  CLEAR_PESANAN_ITEMS: "CLEAR_PESANAN_ITEMS",
};

export default PesananActionTypes;
