const PesananActionTypes = {
  TOGGLE_CHECKOUT_MODAL_HIDDEN: "TOGGLE_CHECKOUT_MODAL_HIDDEN",
  ADD_ITEM_PESANAN: "ADD_ITEM_PESANAN",
  REMOVE_ITEM_PESANAN: "REMOVE_ITEM_PESANAN",
  CLEAR_ITEM_FROM_PESANAN: "CLEAR_ITEM_FROM_PESANAN",
};

export default PesananActionTypes;
