const MenuByIdActionTypes = {
  FETCH_MENUBYID_START: "FETCH_MENUBYID_START",
  FETCH_MENUBYID_SUCCESS: "FETCH_MENUBYID_SUCCESS",
  FETCH_MENUBYID_FAILURE: "FETCH_MENUBYID_FAILURE",
  REMOVE_CURRENT_MENUBYID: "REMOVE_CURRENT_MENUBYID",
  TOGGLE_IS_UPLOADING: "TOGGLE_IS_UPLOADING",
};

export default MenuByIdActionTypes;
