const UsersActionTypes = {
  FETCH_PEGAWAI_START: "FETCH_PEGAWAI_START",
  FETCH_PEGAWAI_SUCCESS: "FETCH_PEGAWAI_SUCCESS",
  FETCH_PEGAWAI_FAILURE: "FETCH_PEGAWAI_FAILURE",
  IS_EMAIL_EXIST: "IS_EMAIL_EXIST",
  TOGGLE_SHOW_MODAL_PEGAWAI: "TOGGLE_SHOW_MODAL_PEGAWAI",
};

export default UsersActionTypes;
