const UsersActionTypes = {
  FETCH_PEGAWAI_START: "FETCH_PEGAWAI_START",
  FETCH_PEGAWAI_SUCCESS: "FETCH_PEGAWAI_SUCCESS",
  FETCH_PEGAWAI_FAILURE: "FETCH_PEGAWAI_FAILURE",
};

export default UsersActionTypes;
