const DetailPesananActionTypes = {
  FETCH_DETAIL_PESANAN_START: "FETCH_DETAIL_PESANAN_START",
  FETCH_DETAIL_PESANAN_SUCCESS: "FETCH_DETAIL_PESANAN_SUCCESS",
  FETCH_DETAIL_PESANAN_FAILURE: "FETCH_DETAIL_PESANAN_FAILURE",
  REMOVE_DATA_DETAIL_PESANAN: "REMOVE_DATA_DETAIL_PESANAN",
  TOGGLE_IS_UPLOADING_DETAIL_PESANAN: "TOGGLE_IS_UPLOADING_DETAIL_PESANAN",
};

export default DetailPesananActionTypes;
