const MenuActionTypes = {
  FETCH_MENU_START: "FETCH_MENU_START",
  FETCH_MENU_SUCCESS: "FETCH_MENU_SUCCESS",
  FETCH_MENU_FAILURE: "FETCH_MENU_FAILURE",
  TOGGLE_SHOW_MODAL_ADD_MENU: "TOGGLE_SHOW_MODAL_ADD_MENU",
  TOGGLE_SHOW_MODAL_DELETE_MENU: "TOGGLE_SHOW_MODAL_DELETE_MENU",
  TOGGLE_SHOW_MODAL_UPDATE_MENU: "TOGGLE_SHOW_MODAL_UPDATE_MENU",
  SET_INPUT_PROFILE_MENU: "SET_INPUT_PROFILE_MENU",
  REMOVE_INPUT_PROFILE_MENU: "REMOVE_INPUT_PROFILE_MENU",
  SET_SEARCH_MENU_FIELD: "SET_SEARCH_MENU_FIELD",
  TOGGLE_IS_UPLOADING_MENU: "TOGGLE_IS_UPLOADING_MENU",
};

export default MenuActionTypes;
