const MenuActionTypes = {
  FETCH_MENU_START: "FETCH_MENU_START",
  FETCH_MENU_SUCCESS: "FETCH_MENU_SUCCESS",
  FETCH_MENU_FAILURE: "FETCH_MENU_FAILURE",
  TOGGLE_SHOW_MODAL_ADD_MENU: "TOGGLE_SHOW_MODAL_ADD_MENU",
  TOGGLE_SHOW_MODAL_DELETE_MENU: "TOGGLE_SHOW_MODAL_DELETE_MENU",
  SET_INPUT_PROFILE: "SET_INPUT_PROFILE",
  REMOVE_INPUT_PROFILE: "REMOVE_INPUT_PROFILE",
  TOGGLE_IS_UPLOADING: "TOGGLE_IS_UPLOADING",
};

export default MenuActionTypes;
