const UserByIdActionTypes = {
  FETCH_USERBYID_START: "FETCH_USERBYID_START",
  FETCH_USERBYID_SUCCESS: "FETCH_USERBYID_SUCCESS",
  FETCH_USERBYID_FAILURE: "FETCH_USERBYID_FAILURE",
  REMOVE_CURRENT_USERBYID: "REMOVE_CURRENT_USERBYID",
};

export default UserByIdActionTypes;
